namespace ForzaTelemetry.ForzaModels.DataOut.FormulaOne.Enums;

public enum TrackIDsEnum {
    Melbourne,
    PaulRicard,
    Shanghai,
    Bahrain,
    Catalunya,
    Monaco,
    Montreal,
    Silverstone,
    Hockenheim,
    Hungaroring,
    Spa,
    Monza,
    Singapore,
    Suzuka,
    AbuDhabi,
    Texas,
    Brazil,
    Austria,
    Sochi,
    Mexico,
    Azerbaijan,
    BahrainShort,
    SilverstoneShort,
    TexasShort,
    SuzukaShort,
    Hanoi,
    Zandvoort,
    Imola,
    Portimao,
    Jeddah,
    Miami
}